import { useEffect, useState } from 'react'
import { ArrowLeft, Send } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import api from '../api'
import Loading from '../components/Loading'
import Badge from '../components/Badge'
export default function ConversationDetail() {
  const { id } = useParams(); const [conversation, setConversation] = useState(null); const [text, setText] = useState(''); const [error, setError] = useState('')
  useEffect(() => { api.get(`/conversations/${id}`).then(r => setConversation(r.data)).catch(e => setError(e.response?.data?.detail || 'Conversation not found.')) }, [id])
  const send = async e => { e.preventDefault(); if (!text.trim()) return; try { const { data } = await api.post(`/conversations/${id}/messages`, { role: 'agent', content: text }); setConversation(data); setText('') } catch { setError('Message could not be sent.') } }
  if (!conversation && !error) return <Loading />
  if (error) return <div className="rounded-xl bg-rose-50 p-5 text-rose-600">{error}</div>
  return <><Link to="/conversations" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-indigo-600"><ArrowLeft size={16}/> Back to conversations</Link><div className="grid gap-6 lg:grid-cols-3"><section className="card lg:col-span-2"><div className="flex items-start justify-between border-b p-5"><div><h1 className="text-xl font-black">{conversation.customer_name}</h1><p className="mt-1 text-sm text-slate-500">{conversation.email}</p></div><div className="flex gap-2"><Badge value={conversation.status}/><Badge value={conversation.priority}/></div></div><div className="space-y-4 p-5">{conversation.messages?.map((m, i) => <div key={i} className={`flex ${m.role === 'agent' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 ${m.role === 'agent' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700'}`}><p className="text-xs font-bold opacity-70">{m.role}</p><p className="mt-1">{m.content}</p><p className="mt-2 text-[10px] opacity-60">{m.timestamp && new Date(m.timestamp).toLocaleString()}</p></div></div>)}</div><form onSubmit={send} className="flex gap-2 border-t p-4"><input value={text} onChange={e => setText(e.target.value)} placeholder="Write a reply…" className="flex-1 rounded-xl border px-4 outline-none focus:border-indigo-500"/><button className="btn-primary flex items-center gap-2"><Send size={16}/> Send</button></form></section><aside className="card h-fit p-5"><h2 className="font-bold">Conversation details</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-400">Conversation ID</dt><dd className="mt-1 font-medium">{conversation.id}</dd></div><div><dt className="text-slate-400">Customer</dt><dd className="mt-1 font-medium">{conversation.customer_name}</dd></div><div><dt className="text-slate-400">Priority</dt><dd className="mt-1"><Badge value={conversation.priority}/></dd></div></dl></aside></div></>
}
