import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Search, Plus } from 'lucide-react'
import api from '../api'
import Loading from '../components/Loading'
import Badge from '../components/Badge'
export default function Conversations() {
  const [items, setItems] = useState(null); const [query, setQuery] = useState(''); const [status, setStatus] = useState('')
  useEffect(() => { api.get('/conversations', { params: status ? { status } : {} }).then(r => setItems(r.data)).catch(() => setItems([])) }, [status])
  const filtered = (items || []).filter(c => `${c.customer_name} ${c.email}`.toLowerCase().includes(query.toLowerCase()))
  return <><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Conversations</h1><p className="mt-1 text-slate-500">Review and respond to customer conversations.</p></div><button className="btn-primary flex items-center gap-2"><Plus size={17}/> New conversation</button></div><div className="card overflow-hidden"><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input placeholder="Search customers…" value={query} onChange={e => setQuery(e.target.value)} className="w-full rounded-xl border py-2.5 pl-10 pr-3 outline-none focus:border-indigo-500"/></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border px-3 text-sm text-slate-600 outline-none"><option value="">All statuses</option><option>open</option><option>pending</option><option>resolved</option><option>closed</option></select></div>{!items ? <Loading/> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3">Messages</th></tr></thead><tbody className="divide-y">{filtered.map(c => <tr key={c.id} className="hover:bg-slate-50"><td className="px-5 py-4"><Link to={`/conversations/${c.id}`} className="font-bold text-indigo-700 hover:underline">{c.customer_name}</Link><div className="text-xs text-slate-400">{c.email}</div></td><td className="px-5 py-4"><Badge value={c.status}/></td><td className="px-5 py-4"><Badge value={c.priority}/></td><td className="px-5 py-4 text-slate-500">{c.messages?.length || 0}</td></tr>)}</tbody></table>{!filtered.length && <div className="p-10 text-center text-slate-500">No conversations found.</div>}</div>}</div></>
}
