import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Database, FileSearch, MessageSquare, ShieldAlert, ShieldCheck } from 'lucide-react'
import api from '../api'
import Loading from '../components/Loading'
import Badge from '../components/Badge'

const fallback = { total_conversations: 0, sentiment_breakdown: {}, top_categories: [], frequently_reported_issues: [], risk_breakdown: {}, coverage: {} }
const levels = [['critical', 'Immediate attention', 'bg-rose-50 text-rose-700'], ['high', 'Review soon', 'bg-orange-50 text-orange-700'], ['medium', 'Monitor', 'bg-amber-50 text-amber-700'], ['low', 'Routine', 'bg-emerald-50 text-emerald-700']]

export default function Dashboard() {
  const [stats, setStats] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.get('/dashboard-stats').then(r => setStats(r.data)).catch(e => setError(e.response?.data?.detail || 'Could not load dashboard.')) }, [])
  if (!stats && !error) return <Loading />
  const s = { ...fallback, ...(stats || {}) }; const sentiments = ['positive', 'neutral', 'negative']; const total = s.total_conversations || 0
  const coverage = s.coverage || { summary: total, risk: total, phishing: 0, social_engineering: 0 }
  const risk = s.risk_breakdown || {}
  return <><div className="mb-8"><h1 className="text-2xl font-black text-slate-900">Good morning 👋</h1><p className="mt-1 text-slate-500">A clear view of your dataset, preprocessing, and customer risk signals.</p></div>{error && <div className="mb-5 rounded-xl bg-rose-50 p-4 text-rose-600">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Database, 'Dataset', `${total} conversations`, 'text-indigo-600'], [FileSearch, 'Preprocessing & issues', `${s.frequently_reported_issues?.length || 0} issue types`, 'text-violet-600'], [ShieldAlert, 'Security coverage', `${coverage.phishing || 0} phishing flags`, 'text-rose-600'], [CheckCircle2, 'Resolved', `${s.resolved_count || 0} conversations`, 'text-emerald-600']].map(([Icon, label, value, color]) => <div className="card p-5" key={label}><Icon className={color} size={22}/><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><MessageSquare size={19} className="text-indigo-600"/><h2 className="font-bold">Sentiment (3 classes)</h2></div><div className="mt-5 grid grid-cols-3 gap-3">{sentiments.map(label => <div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{s.sentiment_breakdown?.[label] || 0}</p><div className="mt-3 h-2 rounded-full bg-slate-200"><div className={`h-2 rounded-full ${label === 'positive' ? 'bg-emerald-500' : label === 'negative' ? 'bg-rose-500' : 'bg-slate-400'}`} style={{ width: `${total ? ((s.sentiment_breakdown?.[label] || 0) / total) * 100 : 0}%` }}/></div></div>)}</div><h2 className="mt-7 font-bold">Categories & extracted issues</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{(s.top_categories || []).slice(0, 6).map(item => <div key={item.name} className="flex justify-between rounded-lg border px-3 py-2 text-sm"><span>{item.name}</span><strong>{item.count}</strong></div>)}{!s.top_categories?.length && <p className="text-sm text-slate-400">No category data yet.</p>}</div></section>
      <section className="card p-5"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck size={19} className="text-indigo-600"/> Risk levels</h2><div className="mt-5 space-y-3">{levels.map(([level, text, color]) => <div key={level} className={`flex items-center justify-between rounded-xl px-3 py-3 ${color}`}><span className="text-sm font-bold capitalize">{level}</span><span className="text-sm">{risk[level] || 0} · {text}</span></div>)}</div><h2 className="mt-7 font-bold">Analysis coverage</h2><div className="mt-3 space-y-2 text-sm text-slate-600">{[['Summary', coverage.summary], ['Risk', coverage.risk], ['Phishing', coverage.phishing], ['Social engineering', coverage.social_engineering]].map(([label, count]) => <div className="flex justify-between" key={label}><span>{label}</span><strong>{count || 0}</strong></div>)}</div></section></div>
    <section className="card mt-6 p-5"><h2 className="font-bold">Extracted issue signals</h2><p className="mt-1 text-sm text-slate-500">Preprocessing groups conversations into recurring customer issues.</p><div className="mt-4 flex flex-wrap gap-2">{(s.frequently_reported_issues || []).map(item => <span key={item.issue} className="rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-semibold text-indigo-700">{item.issue} <span className="ml-1 text-indigo-400">{item.count}</span></span>)}{!s.frequently_reported_issues?.length && <span className="text-sm text-slate-400">No issues extracted yet.</span>}</div></section>
  </>
}
